# Project
version=9.0.0
group=com.mrbysco.roughlyenoughprofessions

# Common
minecraft_version=26.2
neoform_version=26.2-1
mixin_version=0.17.3+mixin.0.8.7
mixinextras_version=0.5.4

# NeoForge
neo_version=26.2.0.7-beta

# Fabric
fabric_version=0.154.0+26.2
fabric_loader_version=0.19.3

# Dependencies
rei_version=26.2.820
architectury_version=21.0.2
cloth_config_version=26.2.155

# Mod options
mod_name=RoughlyEnoughProfessions
mod_author=Mrbysco
mod_id=roughlyenoughprofessions

#Publishing
curseforge_id=597988
modrinth_id=V8XJ8f5f

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false