# Project
version=4.0.3
group=com.mrbysco.roughlyenoughprofessions

# Common
minecraft_version=1.21.4

# NeoForge
neo_version=21.4.136
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.119.2+1.21.4
fabric_loader_version=0.16.11

# Dependencies
rei_version=18.0.808
architectury_version=15.0.3
cloth_config_version=17.0.144

# Mod options
mod_name=RoughlyEnoughProfessions
mod_author=Mrbysco
mod_id=roughlyenoughprofessions

#Publishing
curseforge_id=597988
modrinth_id=V8XJ8f5f

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false