# Project
version=5.0.0
group=com.mrbysco.roughlyenoughprofessions

# Common
minecraft_version=1.21.8
neoform_version=1.21.8-20250717.133445
mixin_version=0.15.0+mixin.0.8.7
mixinextras_version=0.4.1

# NeoForge
neo_version=21.8.47
parchment_minecraft_version=1.21.8
parchment_mapping_version=2025.07.20

# Fabric
fabric_version=0.133.4+1.21.8
fabric_loader_version=0.17.2

# Dependencies
rei_version=20.0.811
architectury_version=17.0.8
cloth_config_version=19.0.147

# Mod options
mod_name=RoughlyEnoughProfessions
mod_author=Mrbysco
mod_id=roughlyenoughprofessions

#Publishing
curseforge_id=597988
modrinth_id=V8XJ8f5f

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false